### ISSUE TITLE
[RESOLVED] Malwarebytes flags 'elevate.exe' as malicious

### ISSUE THREAD

**Issue by gitdine** [bongochong/CWP-Utilities#3]
[VirusTotal results](https://www.virustotal.com/gui/file/433c4d7c9294c371eb38af4018d1fe5296f68326302541a5f2c880ced6eac251/detection)

Might be worth informing users that this is a false positive.

**Comment by bongochong** [comment]
It's in the *disclaimer* section of the readme, but I'll get around to re-wording it so the relation to Kai Liu's little tool is more clear. The unfortunate situation is that every single utility available for performing that function sets *something* off, so I just stuck with one that triggered the least amount of engines, and whose source is redistributable. I plan to eventually move to another method of elevating batch script privileges (probably pascal-based), though want to make sure it works on as many platforms as possible. It's only necessary for the hosts file scripts BTW.
